name: Publish NPM Package

concurrency: publish

on:
  push:
    tags:
      - "v*.*.*" # Trigger only on version tags

permissions:
  id-token: write # Grants write access to id-token for provenance
  contents: read # Ensures the workflow can read repository contents

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 23, 24]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install
        run: npm i

      - name: Unit tests
        run: npm test

      - name: Integration tests
        run: |
          set -euo pipefail
          echo "Looking for subfolders in test_integration/..."
          for d in test_integration/*; do
            if [ -d "$d" ]; then
              echo "--- Entering $d ---"
              if [ -f "$d/package.json" ]; then
                (cd "$d" && npm i && npm test)
              else
                echo "skipping $d (no package.json)"
              fi
            fi
          done

  deploy-and-publish:
    runs-on: ubuntu-latest
    needs: integration_test
    environment: publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tag version
        id: tag_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "Tag version: $TAG_VERSION"

      - name: Get package.json version
        id: package_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "Package.json version: $PACKAGE_VERSION"

      - name: Compare versions
        run: |
          if [ "${{ steps.tag_version.outputs.version }}" != "${{ steps.package_version.outputs.version }}" ]; then
            echo "Error: Tag version (${{ steps.tag_version.outputs.version }}) does not match package.json version (${{ steps.package_version.outputs.version }})"
            exit 1
          fi
          echo "Version match confirmed: ${{ steps.tag_version.outputs.version }}"

      - uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"
          registry-url: "https://registry.npmjs.org/"

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install
        run: npm i

      - name: Unit tests & coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./gh_pages/coverage
          fail_ci_if_error: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh_pages

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
