name: Unsupported Tests

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Clean NPM Cache
        run: npm cache clean --force

      - name: Install
        run: npm i

      - name: Unsupported tests
        run: npm run test:u
