name: integration tests

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 23, 24]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm i

    - name: Run build
      run: npm run build

    - name: Run install & tests in test_integration subfolders
      run: |
        set -euo pipefail
        echo "Looking for subfolders in test_integration/..."
        for d in test_integration/*; do
          if [ -d "$d" ]; then
            echo "--- Entering $d ---"
            if [ -f "$d/package.json" ]; then
              (cd "$d" && npm i && npm test)
            else
              echo "skipping $d (no package.json)"
            fi
          fi
        done